stages:
  data_injestion:
    cmd: python src/data_injestion.py
    deps:
    - src/data_injestion.py
    params:
    - data_injestion.test_size
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - data/raw
    - src/data_preprocessing.py
    outs:
    - data/interim
  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
    - data/interim
    - src/feature_engineering.py
    params:
    - feature_engineering.max_features
    outs:
    - data/processed
  model_buliding:
    cmd: python src/model_buliding.py
    deps:
    - data/processed
    - src/model_buliding.py
    params:
    - model_buliding.n_estimators
    - model_buliding.random_state
    outs:
    - models/model.pkl
  model_evalulation:
    cmd: python src/model_evalulation.py
    deps:
    - models/model.pkl
    - src/model_evalulation.py
    metrics:
    - reports/metrics.json
params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step